server: true
auto: true
markdown: rdiscount
pygments: true
paginate: 5

title: Suck&Bunny
url: suckbunny.cn
author: 
    name: suckbunny
    email: bunnypaladin@gmail.com
description: "My Blog"

about: "æˆ‘åªæ˜¯ä¸€ä¸ªç»Ÿè®¡æœ¬ç§‘æ¯•ä¸šçš„R&LaTeX&knitrçˆ±å¥½è€?"
follow: 
    github: https://github.com/suckbunny
    gmail:  https://plus.google.com/u/0/?tab=wX
description: "My Blog"
style: /css/style.css
blogName: LoveBunny
blogDesc: æ¥ä¸‹å»çš„è·¯æˆ‘ä»¬ä¸€èµ·èµ°è¿?
